spring.application.name=bank-grpc-graph-service
grpc.server.address=*
grpc.server.port=50051
grpc.server.security.enabled=false
spring.data.mongodb.uri=mongodb://localhost:27017/grpc-database
server.port=8080
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
logging.level.org.springframework.graphql=off 
#turn the loggin.level... to DEBUG to see the stack trace in the console