spring.application.name=bank-grpc-graph-service
server.port=8082
grpc.client.bankService.address=static://localhost:50051
grpc.client.bankService.negotiation-type=plaintext
spring.jackson.serialization.indent-output=true